FROM tomcat:11.0.24-jdk17-temurin

# Remove default ROOT app. you can remove this line, not mandatory
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy your WAR as ROOT.war
COPY target/myweb-8.8.2.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
